#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'apt', '= 1.10.0'
cookbook 'apache2', '>= 1.0.0'
cookbook 'database'
cookbook 'mysql'
cookbook 'nginx'
cookbook 'php'
cookbook 'varnish'
